# Copyright 2021 Envoyproxy Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
FROM node:16

ENV BUF_VERSION=0.54.1

# Install buf for managing *.proto gen in a single command, also to build the proto descriptor file.
ADD https://github.com/bufbuild/buf/releases/download/v${BUF_VERSION}/buf-Linux-x86_64 /usr/local/bin/buf
RUN chmod +x /usr/local/bin/buf

COPY . /app
WORKDIR /app

# Install all dependencies.
RUN yarn install --production

# Generate proto descriptor file from the defined buf.gen.yaml.
RUN buf build -o helloworld.bin

# Serve the backend service.
CMD ["node", "server"]
