version: "3.7"
services:
  front-envoy:
    image: dio123/envoy:h2-trailers-debug
    command: -c /etc/envoy.yaml
    volumes:
      - ./envoy.yaml:/etc/envoy.yaml
    networks:
      - envoymesh
    ports:
      - "8000:8000"
      - "8080:8080"
      - "9901:9901"

  greeter-backend:
    build:
      context: .
      dockerfile: Dockerfile-greeter-backend
    networks:
      envoymesh:
        aliases:
          - greeter-backend

  greeter-frontend:
    build:
      context: .
      dockerfile: Dockerfile-greeter-frontend
    networks:
      envoymesh:
        aliases:
          - greeter-frontend
    ports:
      - "5000:5000"

networks:
  envoymesh: {}
